# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l6SVz-0pLVJ-Qn9pf-_CDYp_yzldOeou
"""

import cv2
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
from google.colab import files

# Upload Image
uploaded = files.upload()
image_path = list(uploaded.keys())[0]

# Read Image
img = cv2.imread(image_path)
img = cv2.resize(img, (128,128))
img = img / 255.0

# Convert to grayscale for simple mask creation
gray = cv2.cvtColor((img*255).astype(np.uint8), cv2.COLOR_BGR2GRAY)

# Create simple binary mask using threshold
_, mask = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
mask = mask / 255.0
mask = np.expand_dims(mask, axis=-1)

# Expand dimensions for CNN
X = np.expand_dims(img, axis=0)
y = np.expand_dims(mask, axis=0)

# Build Simple CNN Segmentation Model
model = models.Sequential([
    layers.Conv2D(32, 3, activation='relu', padding='same', input_shape=(128,128,3)),
    layers.MaxPooling2D(),
    layers.Conv2D(64, 3, activation='relu', padding='same'),
    layers.UpSampling2D(),
    layers.Conv2D(1, 1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train on single image (Demo only)
model.fit(X, y, epochs=20)

# Predict
prediction = model.predict(X)

# Display Results
plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.title("Input Image")
plt.imshow(img)

plt.subplot(1,3,2)
plt.title("Generated Mask")
plt.imshow(mask.squeeze(), cmap='gray')

plt.subplot(1,3,3)
plt.title("CNN Predicted Mask")
plt.imshow(prediction[0].squeeze(), cmap='gray')

plt.show()

import cv2

# Convert the prediction to an 8-bit image
predicted_mask_8bit = (prediction[0].squeeze() * 255).astype(np.uint8)

# Save the predicted mask
cv2.imwrite('predicted_mask.png', predicted_mask_8bit)
print("Predicted mask saved as 'predicted_mask.png'")

import cv2
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
from google.colab import files

# Upload Image
uploaded = files.upload()
image_path = list(uploaded.keys())[0]

# Read Image
img = cv2.imread(image_path)
img = cv2.resize(img, (128,128))
img = img / 255.0

# Convert to grayscale for simple mask creation
gray = cv2.cvtColor((img*255).astype(np.uint8), cv2.COLOR_BGR2GRAY)

# Create simple binary mask using threshold
_, mask = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
mask = mask / 255.0
mask = np.expand_dims(mask, axis=-1)

# Expand dimensions for CNN
X = np.expand_dims(img, axis=0)
y = np.expand_dims(mask, axis=0)

# Build Simple CNN Segmentation Model
model = models.Sequential([
    layers.Conv2D(32, 3, activation='relu', padding='same', input_shape=(128,128,3)),
    layers.MaxPooling2D(),
    layers.Conv2D(64, 3, activation='relu', padding='same'),
    layers.UpSampling2D(),
    layers.Conv2D(1, 1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train on single image (Demo only)
model.fit(X, y, epochs=20)

# Predict
prediction = model.predict(X)

# Display Results
plt.figure(figsize=(12,4))

plt.subplot(1,3,1)
plt.title("Input Image")
plt.imshow(img)

plt.subplot(1,3,2)
plt.title("Generated Mask")
plt.imshow(mask.squeeze(), cmap='gray')

plt.subplot(1,3,3)
plt.title("CNN Predicted Mask")
plt.imshow(prediction[0].squeeze(), cmap='gray')

plt.show()
